apiVersion: charts.ta.cloud.ibm.com/v1
kind: TransAdv
metadata:
  name: ta
  labels:
    release: "operator"
    app.kubernetes.io/name: ta-operator
    app.kubernetes.io/instance: ta-instance
    app.kubernetes.io/managed-by: helm
spec:

  demo:
    enabled: true

  networkPolicy:
    enabled: true

  route:
    enabled: true
    hostname: "ta-apps.{{ clusterSubdomain }}"
  # Internal TLS communication among pods
  #
  # Set to true to enable.
  # If true, also provide the caCert value i.e. the ca cert that signs the public certificate.
  # This value is available in the installation script's output as public.crt
  # Each line of the value have 2 spaces indentation to the key 'caCert'.
  #
  # If you do not provide a caCert value, one will be generated
  #
  # If false, the caCert value will be ignored.
  tls:
    enabled: true
    caCert: |
      {{ taGeneratedCaCert | indent(6) }}

  authentication:
    disabled:
      liberty: false
      ui: false
    ocp:
      authIssuerEndpoint: "{{ cluster.authorizationEndpoint | regex_replace('/oauth/.*', '') }}"
      apiEndpoint: "{{ clusterUrl }}"
      secretName: "transformation-advisor-secret"
    oidc:
      endpointPort: "{{ cluster.authorizationEndpoint | urlsplit('port') }}"
      clientId: ta-ui
      clientSecret: "{{ lookup('password', '/dev/null length=40 chars=hexdigits') }}"

  # Default values for couchdb.
  couchdb:
    image: "{{ icpa.registry }}{{ icpa.ta.registryNamespace }}/transadv-db:2.0.5"
    imagePullSecret: "{{ icpa.pullSecret }}"
    ## Configure resource requests and limits
    ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 8Gi
        cpu: 16000m
    livenessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 3
      periodSeconds: 5
      failureThreshold: 6
    readinessProbe:
      initialDelaySeconds: 5
      timeoutSeconds: 3
      periodSeconds: 5
      failureThreshold: 6

    ## Enable persistence using Persistent Volume Claims
    ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
    ##
    persistence:
      enabled: true # default to use PV
      accessMode: "ReadWriteMany"
      size: 8Gi
      useDynamicProvisioning: true

      ## A manually managed Persistent Volume and Claim
      ## Requires persistence.enabled: true
      ## If defined, PVC must be created manually before volume will be bound
      ##
      existingClaim: ""

      ##incase of minikube hostpath volume set to MANUAL
      storageClassName: "ibmc-block-gold"

      supplementalGroups: []
  # Default values for transformation advisor.
  transadv:
    image: "{{ icpa.registry }}{{ icpa.ta.registryNamespace }}/transadv-server:2.0.5"
    imagePullSecret: "{{ icpa.pullSecret }}"
    publicUrl: "https://ta-apps.{{ clusterSubdomain }}" # change to place holder
    logLevel: "info" # liberty log level, accept: trace, debug, info, warn, error
    ## Configure resource requests and limits
    ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 4Gi
        cpu: 16000m
    livenessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 3
      periodSeconds: 5
      failureThreshold: 6
    readinessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 3
      periodSeconds: 5
      failureThreshold: 6

  # Default values for transformation advisor ui.
  transadvui:
    image: "{{ icpa.registry }}{{ icpa.ta.registryNamespace }}/transadv-ui:2.0.5"
    imagePullSecret: "{{ icpa.pullSecret }}"
    logLevel: "info" # ui log level, accept: error, warn, info, verbose, debug, silly
    useSecureCookie: "true" # use true only on https ta ui endpoint, otherwise false
    ## Configure resource requests and limits
    ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 4Gi
        cpu: 16000m
    livenessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 5
      periodSeconds: 30
      failureThreshold: 6
    readinessProbe:
      initialDelaySeconds: 5
      timeoutSeconds: 5
      periodSeconds: 30
      failureThreshold: 6
